### ISSUE TITLE
[ERROR] Adding articles with null/empty names.

### ISSUE THREAD

**Issue by titandino** [DarkanRS/core#45]
Index 0 out of bounds for length 0
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.rs.lib.util.Utils.addArticle(Utils.java:1700)
	at com.rs.net.decoders.handlers.ObjectHandler.handleOptionExamine(ObjectHandler.java:1897)
	at com.rs.net.decoders.handlers.impl.ObjectOptionHandler.handle(ObjectOptionHandler.java:44)
	at com.rs.net.decoders.handlers.impl.ObjectOptionHandler.handle(ObjectOptionHandler.java:28)
	at com.rs.game.model.entity.player.Player.processPackets(Player.java:3808)
	at com.rs.game.model.entity.player.Player.processEntity(Player.java:992)
	at com.rs.cores.WorldThread.run(WorldThread.java:72)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by titandino** [comment]
Fixed
